openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
  - name: Contacts
    description: Operations about contacts.
servers:
  - url: http://127.0.0.1:3000
  - url: https://students-base-2.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
